# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTaskRunnerInstaller@0
  inputs:
    nodeVersion: '6'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '.'
  displayName: 'install'  

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '.'
    customCommand: 'npm run build'
  displayName: 'build'
    
- task: CopyPublishBuildArtifacts@1
  inputs:
    CopyRoot: 'build'
    Contents: 'npm build'
    ArtifactName: 'build'
    ArtifactType: 'Container'
  displayName: 'artifacts'